name: Collector

on:
  workflow_dispatch:
    inputs:
      commit-message:
        description: 'Commit message for collected artifacts.'
        required: false

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build CLI
        run: npm run build
      - name: Generate portfolio snapshot
        run: node dist/cli/index.js export --stdout
      - name: Configure git user
        run: |
          git config user.name "orchestrator-bot"
          git config user.email "orchestrator@example.com"
      - name: Commit artifacts
        run: |
          git add artifacts/
          if git diff --cached --quiet; then
            echo "No artifact changes to commit"
            exit 0
          fi
          git commit -m "${{ github.event.inputs.commit-message || 'Collect orchestrator artifacts' }}"
          git push
